#-*- coding:utf-8 -*-

import urllib
import simplejson as json
import matplotlib.pyplot as plt
from datetime import datetime
from data import get_commodity_data

# Show the star
# Parameters:asin
# Return the number of the star
def getstar(asin):
	data = get_commodity_data(asin)
	star=float(data['stats_info']['avg_info'])
	result=str(star)
	return result

def highchart(asin):
	star = getstar(asin)
	content='''<script>'''
	content+='''$(function () {'''
	content+='''$('#speedstar').highcharts({'''
	content+='''chart: {'''
	content+='''type: 'gauge','''
	content+='''plotBackgroundColor: null,'''
	content+='''plotBackgroundImage: null,'''
	content+='''plotBorderWidth: 0,'''
	content+='''plotShadow: false'''
	content+='''},'''
	content+='''title: {'''
	content+='''text: 'Star' '''
	content+='''},'''
	content+='''pane: {'''
	content+='''startAngle: -150,'''
	content+='''endAngle: 150,'''
	content+='''background: [{'''
	content+='''backgroundColor: {'''
	content+='''linearGradient: { x1: 0, y1: 0, x2: 0, y2: 1 },'''
	content+='''stops: ['''
	content+='''[0, '#FFF'],'''
	content+='''[1, '#333']'''
	content+=''']'''
	content+='''},'''
	content+='''borderWidth: 0,'''
	content+='''outerRadius: '109%' '''
	content+='''}, {'''
	content+='''backgroundColor: {'''
	content+='''linearGradient: { x1: 0, y1: 0, x2: 0, y2: 1 },'''
	content+='''stops: ['''
	content+='''[0, '#333'],'''
	content+='''[1, '#FFF']'''
	content+=''']'''
	content+='''},'''
	content+='''borderWidth: 1,'''
	content+='''outerRadius: '107%' '''
	content+='''}, {'''
	content+=''''''
	content+='''}, {'''
	content+='''backgroundColor: '#DDD','''
	content+='''borderWidth: 0,'''
	content+='''outerRadius: '105%','''
	content+='''innerRadius: '103%' '''
	content+='''}]'''
	content+='''},'''
	content+=''''''
	content+='''yAxis: {'''
	content+='''min: 0,'''
	content+='''max: 5,'''
	content+='''minorTickInterval: 'auto','''
	content+='''minorTickWidth: 1,'''
	content+='''minorTickLength: 10,'''
	content+='''minorTickPosition: 'inside','''
	content+='''minorTickColor: '#666','''
	content+='''tickPixelInterval: 30,'''
	content+='''tickWidth: 2,'''
	content+='''tickPosition: 'inside','''
	content+='''tickLength: 10,'''
	content+='''tickColor: '#666','''
	content+='''labels: {'''
	content+='''step: 2,'''
	content+='''rotation: 'auto' '''
	content+='''},'''
	content+='''title: {'''
	content+='''text: 'star' '''
	content+='''},'''
	content+='''plotBands: [{'''
	content+='''from: 0,'''
	content+='''to: 1,'''
	content+='''color: '#55BF3B' '''
	content+='''}, {'''
	content+='''from: 1,'''
	content+='''to: 2,'''
	content+='''color: '#DDDF0D' '''
	content+='''}, {'''
	content+='''from: 2,'''
	content+='''to: 3,'''
	content+='''color: '#DF5353' '''
	content+='''}, {'''
	content+='''from: 3,'''
	content+='''to: 4,'''
	content+='''color: '#DDDF0D' '''
	content+='''}, {'''
	content+='''from: 4,'''
	content+='''to: 5,'''
	content+='''color: '#55BF3B' '''
	content+='''}]'''
	content+='''},'''
	content+='''series: [{'''
	content+='''name: 'Speed','''
	content+='''data: ['''
	content+=star
	content+='''],'''
	content+='''tooltip: {'''
	content+='''valueSuffix: ' star' '''
	content+='''}'''
	content+='''}]'''
	content+='''}, '''
	content+=''''''
	content+='''function (chart) {'''
	content+='''if (!chart.renderer.forExport) {'''
	content+='''setInterval(function () {'''
	content+='''var point = chart.series[0].points[0],'''
	content+='''newVal,'''
	content+='''inc = 0;'''        
	content+='''newVal = point.y + inc;'''
	content+='''if (newVal < 0 || newVal > 200) {'''
	content+='''newVal = point.y - inc;'''
	content+='''}'''
	content+='''point.update(newVal);'''  
	content+='''}, 3000);'''
	content+='''}'''
	content+='''});'''
	content+='''});'''
	content+='''</script>'''
	return content
